"use client";
import { useState, useEffect, useRef } from "react";
import {
  getMockPolicies,
  generateCid,
  generateTeeSig,
  addClaim,
  Claim,
  ProcessingStep,
  sleep,
} from "@/lib/data";
import { useAccount, useWriteContract } from "wagmi";
import { parseEther, keccak256, toHex } from "viem";
import { CONTRACT_ADDRESS, INSURANCE_ABI } from "@/lib/contract";

interface Props {
  onSuccess: () => void;
}

const PROCESSING_STEPS: Omit<ProcessingStep, "status" | "timestamp">[] = [
  { label: "Broadcasting claim to 0G Chain", detail: "Calling submitClaim(cid)..." },
  { label: "Uploading evidence to 0G Storage", detail: "Calculating Merkle root..." },
  { label: "Requesting TEE enclave on 0G Compute", detail: "Initializing Intel TDX..." },
  { label: "AI model inference running", detail: "Analyzing claim evidence..." },
  { label: "Enclave signing approval", detail: "ECDSA signature generation..." },
  { label: "Smart contract settling claim", detail: "Verifying TEE signature onchain..." },
  { label: "Payout released to wallet", detail: "settleClaim() executed ✅" },
];

export default function SubmitClaim({ onSuccess }: Props) {
  const [selectedPolicy, setSelectedPolicy] = useState<string>("");
  const [description, setDescription] = useState("");
  const [fileUploaded, setFileUploaded] = useState(false);
  const [fileName, setFileName] = useState("");
  const [isDragOver, setIsDragOver] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [steps, setSteps] = useState<ProcessingStep[]>([]);
  const [currentStep, setCurrentStep] = useState(-1);
  const [done, setDone] = useState(false);
  const [claimData, setClaimData] = useState<{ cid: string; sig: string; txHash: string; payoutTx: string } | null>(null);
  const fileRef = useRef<HTMLInputElement>(null);

  const { address, isConnected } = useAccount();
  const { writeContractAsync } = useWriteContract();

  const policies = getMockPolicies().filter((p) => p.status === "active");

  function handleFileDrop(e: React.DragEvent) {
    e.preventDefault();
    setIsDragOver(false);
    const file = e.dataTransfer.files[0];
    if (file) { setFileUploaded(true); setFileName(file.name); }
  }

  function handleFileChange(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (file) { setFileUploaded(true); setFileName(file.name); }
  }

  async function handleSubmit() {
    if (!selectedPolicy || !description || !isConnected) return;
    setIsSubmitting(true);

    const initialSteps: ProcessingStep[] = PROCESSING_STEPS.map((s) => ({
      ...s,
      status: "pending",
    }));
    setSteps(initialSteps);

    try {
      // Step 1: BroadCast Claim
      setCurrentStep(0);
      setSteps(prev => prev.map((s, i) => i === 0 ? { ...s, status: "running" } : s));
      
      const cid = generateCid();
      const policyObj = policies.find(p => p.id === selectedPolicy);
      const policyIdNum = BigInt(selectedPolicy.split("-")[1]);

      const submitTx = await writeContractAsync({
        address: CONTRACT_ADDRESS,
        abi: INSURANCE_ABI,
        functionName: "submitClaim",
        args: [policyIdNum, cid],
      });
      
      setSteps(prev => prev.map((s, i) => i === 0 ? { ...s, status: "done", timestamp: new Date().toLocaleTimeString(), detail: submitTx.slice(0, 20) + "..." } : s));

      // Step 2: Upload to 0G Storage
      setCurrentStep(1);
      setSteps(prev => prev.map((s, i) => i === 1 ? { ...s, status: "running" } : s));
      await sleep(1500);
      setSteps(prev => prev.map((s, i) => i === 1 ? { ...s, status: "done", timestamp: new Date().toLocaleTimeString(), detail: cid.slice(0, 24) + "..." } : s));

      // Step 3-4: AI Inference in TEE
      setCurrentStep(2);
      setSteps(prev => prev.map((s, i) => i === 2 ? { ...s, status: "running" } : s));
      await sleep(2000);
      setSteps(prev => prev.map((s, i) => i === 2 ? { ...s, status: "done", timestamp: new Date().toLocaleTimeString() } : s));

      setCurrentStep(3);
      setSteps(prev => prev.map((s, i) => i === 3 ? { ...s, status: "running" } : s));
      await sleep(2500);
      setSteps(prev => prev.map((s, i) => i === 3 ? { ...s, status: "done", timestamp: new Date().toLocaleTimeString(), detail: "Score: 0.98 (APPROVED)" } : s));

      // Step 5: TEE Signing
      setCurrentStep(4);
      setSteps(prev => prev.map((s, i) => i === 4 ? { ...s, status: "running" } : s));
      
      // In a real TEE, this is done by the enclave. 
      // For the demo, we use a mock signature that would be generated by the enclave.
      const mockClaimId = BigInt(Math.floor(Math.random() * 1000)); // Should be fetched from event
      const payoutAmount = BigInt(parseEther((policyObj?.coverage || 500).toString()));
      const approved = true;

      // Mock TEE Signature (for demo, this would be signed by the TEE_SIGNER_PRIVATE_KEY)
      const sig = generateTeeSig(); 
      
      await sleep(1500);
      setSteps(prev => prev.map((s, i) => i === 4 ? { ...s, status: "done", timestamp: new Date().toLocaleTimeString(), detail: sig.slice(0, 16) + "..." } : s));

      // Step 6: Settle on Chain
      setCurrentStep(5);
      setSteps(prev => prev.map((s, i) => i === 5 ? { ...s, status: "running" } : s));
      
      // Note: In real life, settleClaim might be called by an automated agent/oracle
      // For the demo user experience, we'll let the user trigger it to show the full flow
      const settleTx = await writeContractAsync({
        address: CONTRACT_ADDRESS,
        abi: INSURANCE_ABI,
        functionName: "settleClaim",
        args: [
          mockClaimId, // In real app, get from logs
          approved,
          payoutAmount,
          sig as `0x${string}`,
          keccak256(toHex(`stub-attestation:${cid}`)),
        ],
      });
      
      setSteps(prev => prev.map((s, i) => i === 5 ? { ...s, status: "done", timestamp: new Date().toLocaleTimeString(), detail: settleTx.slice(0, 20) + "..." } : s));

      // Step 7: Done
      setCurrentStep(6);
      setSteps(prev => prev.map((s, i) => i === 6 ? { ...s, status: "done", timestamp: new Date().toLocaleTimeString() } : s));

      const newClaim: Claim = {
        id: `CLM-${mockClaimId}`,
        policyId: selectedPolicy,
        holder: address || "0x...",
        agentId: "alice.0g",
        type: policyObj?.type || "flight_delay",
        status: "paid",
        submittedAt: new Date().toISOString(),
        evidenceCid: cid,
        submitTxHash: submitTx,
        teeSig: sig,
        payoutTxHash: settleTx,
        payoutAmount: policyObj?.coverage || 500,
        aiScore: 0.98,
        processingSteps: steps,
      };
      addClaim(newClaim);
      setClaimData({ cid, sig, txHash: submitTx, payoutTx: settleTx });
      setDone(true);
    } catch (err) {
      console.error("Claim submission failed:", err);
      setIsSubmitting(false);
    }
  }

  if (done && claimData) {
    return (
      <div className="animate-fade-in" style={{ maxWidth: 680, margin: "0 auto" }}>
        <div style={{ textAlign: "center", marginBottom: 40 }}>
          <div style={{ fontSize: 72, marginBottom: 16 }}>✅</div>
          <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 8 }}>Claim Approved & Paid!</h1>
          <p style={{ color: "var(--text-secondary)" }}>Your claim was verified by the TEE enclave and settled onchain.</p>
        </div>

        {/* Artifact Strip */}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 24 }}>
          <div>
            <div style={{ fontSize: 11, color: "var(--text-muted)", fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 6 }}>
              Submit Tx (0G Chain)
            </div>
            <div className="hash-display" style={{ fontSize: 11 }}>{claimData.txHash.slice(0, 32)}...</div>
          </div>
          <div>
            <div style={{ fontSize: 11, color: "var(--text-muted)", fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 6 }}>
              Payout Tx (0G Chain)
            </div>
            <div className="hash-display" style={{ fontSize: 11, color: "var(--emerald)", borderColor: "rgba(0,255,157,0.2)", background: "rgba(0,255,157,0.06)" }}>
              {claimData.payoutTx.slice(0, 32)}...
            </div>
          </div>
          <div>
            <div style={{ fontSize: 11, color: "var(--text-muted)", fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 6 }}>
              0G Storage CID
            </div>
            <div className="hash-display" style={{ fontSize: 11, color: "var(--violet)", borderColor: "rgba(123,47,255,0.2)", background: "rgba(123,47,255,0.06)" }}>
              {claimData.cid}
            </div>
          </div>
          <div>
            <div style={{ fontSize: 11, color: "var(--text-muted)", fontWeight: 700, letterSpacing: "0.08em", textTransform: "uppercase", marginBottom: 6 }}>
              TEE Signature
            </div>
            <div className="hash-display" style={{ fontSize: 11, color: "var(--emerald)", borderColor: "rgba(0,255,157,0.2)", background: "rgba(0,255,157,0.06)" }}>
              {claimData.sig.slice(0, 40)}...
            </div>
          </div>
        </div>

        {/* Processing Timeline */}
        <div className="card" style={{ marginBottom: 24 }}>
          <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 20 }}>Processing Timeline</h3>
          <div className="timeline">
            {steps.map((step, i) => (
              <div key={i} className="timeline-item">
                <div className="timeline-dot" style={{ background: step.status === "done" ? "var(--emerald)" : "var(--cyan)" }} />
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 8 }}>
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 600, color: "var(--text-primary)" }}>{step.label}</div>
                    {step.detail && (
                      <div style={{ fontSize: 11, color: "var(--text-muted)", fontFamily: "var(--font-mono)", marginTop: 2 }}>
                        {step.detail}
                      </div>
                    )}
                  </div>
                  <span style={{ fontSize: 11, color: "var(--text-muted)", fontFamily: "var(--font-mono)", flexShrink: 0 }}>
                    {step.timestamp}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* TEE Attestation Box */}
        <div className="tee-box" style={{ marginBottom: 24 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 12 }}>
            <span style={{ fontSize: 18 }}>🔐</span>
            <span style={{ fontWeight: 700, fontSize: 14, color: "var(--emerald)" }}>TEE Attestation Verified</span>
            <span className="badge badge-emerald" style={{ marginLeft: "auto" }}>ONCHAIN</span>
          </div>
          <div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.7 }}>
            The AI model ran inside an Intel TDX enclave on 0G Compute. The enclave produced a hardware-bound ECDSA signature over the claim decision. This signature was verified onchain by the smart contract before releasing payout.
          </div>
          <div style={{ marginTop: 12, fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--emerald)", wordBreak: "break-all" }}>
            FULL SIG: {claimData.sig}
          </div>
        </div>

        <div style={{ display: "flex", gap: 12 }}>
          <button className="btn btn-success" style={{ flex: 1 }} onClick={onSuccess}>
            View Claim History →
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="animate-fade-in">
      <div style={{ marginBottom: 32 }}>
        <h1 style={{ fontSize: 28, fontWeight: 800, marginBottom: 4 }}>Submit a Claim</h1>
        <p style={{ color: "var(--text-secondary)" }}>Upload evidence and our TEE-verified AI will process your claim instantly.</p>
      </div>

      {isSubmitting ? (
        <div className="card" style={{ maxWidth: 560 }}>
          <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 24 }}>
            <span style={{ fontSize: 24 }}>⚙️</span>
            <div>
              <h3 style={{ fontSize: 16, fontWeight: 700 }}>Processing Your Claim</h3>
              <p style={{ fontSize: 13, color: "var(--text-secondary)" }}>0G Compute TEE is verifying your evidence...</p>
            </div>
          </div>
          <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
            {steps.map((step, i) => (
              <div key={i} style={{ display: "flex", alignItems: "center", gap: 12, padding: "12px 16px", borderRadius: "var(--radius-md)", background: step.status === "running" ? "rgba(0,212,255,0.08)" : step.status === "done" ? "rgba(0,255,157,0.04)" : "rgba(255,255,255,0.02)", border: `1px solid ${step.status === "running" ? "rgba(0,212,255,0.3)" : step.status === "done" ? "rgba(0,255,157,0.15)" : "rgba(255,255,255,0.04)"}`, transition: "all 0.3s" }}>
                <div style={{ width: 20, height: 20, flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "center" }}>
                  {step.status === "done" && <span style={{ color: "var(--emerald)", fontSize: 16 }}>✓</span>}
                  {step.status === "running" && <span className="animate-blink" style={{ color: "var(--cyan)", fontSize: 16 }}>●</span>}
                  {step.status === "pending" && <span style={{ color: "var(--text-muted)", fontSize: 12 }}>○</span>}
                </div>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 13, fontWeight: 600, color: step.status === "pending" ? "var(--text-muted)" : "var(--text-primary)" }}>
                    {step.label}
                  </div>
                  {step.status !== "pending" && step.detail && (
                    <div style={{ fontSize: 11, color: "var(--text-muted)", fontFamily: "var(--font-mono)" }}>
                      {step.detail}
                    </div>
                  )}
                </div>
                {step.timestamp && (
                  <span style={{ fontSize: 11, color: "var(--text-muted)", fontFamily: "var(--font-mono)" }}>
                    {step.timestamp}
                  </span>
                )}
              </div>
            ))}
          </div>
          <div style={{ marginTop: 20 }}>
            <div className="progress-bar">
              <div className="progress-fill" style={{ width: `${((currentStep + 1) / PROCESSING_STEPS.length) * 100}%` }} />
            </div>
          </div>
        </div>
      ) : (
        <div style={{ maxWidth: 600 }}>
          <div className="card" style={{ marginBottom: 20 }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 16 }}>Claim Details</h3>
            <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
              <div className="form-group">
                <label className="form-label">Select Policy</label>
                <select className="form-input" value={selectedPolicy} onChange={(e) => setSelectedPolicy(e.target.value)}>
                  <option value="">-- Choose a policy --</option>
                  {policies.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.id} — ${p.coverage} {p.type.replace("_", " ")} coverage
                    </option>
                  ))}
                </select>
              </div>

              <div className="form-group">
                <label className="form-label">Claim Description</label>
                <textarea
                  className="form-input"
                  rows={4}
                  placeholder="Describe what happened (e.g., Flight AI-202 was delayed by 3 hours on May 10...)"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  style={{ resize: "vertical" }}
                />
              </div>
            </div>
          </div>

          {/* File Upload */}
          <div className="card" style={{ marginBottom: 20 }}>
            <h3 style={{ fontSize: 15, fontWeight: 700, marginBottom: 16 }}>Evidence Upload</h3>
            <div
              className={`upload-zone ${isDragOver ? "active" : ""}`}
              onDragOver={(e) => { e.preventDefault(); setIsDragOver(true); }}
              onDragLeave={() => setIsDragOver(false)}
              onDrop={handleFileDrop}
              onClick={() => fileRef.current?.click()}
            >
              <input ref={fileRef} type="file" hidden onChange={handleFileChange} accept="image/*,.pdf,.json" />
              {fileUploaded ? (
                <div>
                  <div style={{ fontSize: 36, marginBottom: 8 }}>📄</div>
                  <div style={{ fontSize: 14, fontWeight: 600, color: "var(--emerald)", marginBottom: 4 }}>{fileName}</div>
                  <div style={{ fontSize: 12, color: "var(--text-muted)" }}>Will be uploaded to 0G Storage on submit</div>
                </div>
              ) : (
                <div>
                  <div style={{ fontSize: 36, marginBottom: 8 }}>📁</div>
                  <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 4 }}>Drop evidence file here</div>
                  <div style={{ fontSize: 12, color: "var(--text-muted)" }}>
                    Boarding pass, receipt, photos, or JSON data (max 10MB)
                  </div>
                </div>
              )}
            </div>
            <div style={{ marginTop: 12, padding: "10px 14px", background: "rgba(0,212,255,0.04)", border: "1px solid rgba(0,212,255,0.1)", borderRadius: "var(--radius-sm)", fontSize: 12, color: "var(--text-secondary)" }}>
              📦 Evidence will be stored immutably on <strong style={{ color: "var(--violet)" }}>0G Storage</strong>. A CID will be recorded onchain as proof.
            </div>
          </div>

          {/* TEE Info */}
          <div className="tee-box" style={{ marginBottom: 24 }}>
            <div style={{ display: "flex", gap: 10, alignItems: "flex-start" }}>
              <span style={{ fontSize: 20 }}>🔐</span>
              <div>
                <div style={{ fontWeight: 700, fontSize: 13, color: "var(--emerald)", marginBottom: 4 }}>
                  Privacy by Design
                </div>
                <div style={{ fontSize: 12, color: "var(--text-secondary)", lineHeight: 1.7 }}>
                  Your claim evidence will be processed exclusively inside an Intel TDX secure enclave on <strong>0G Compute</strong>. No human or server can read your data. Only a signed AI decision leaves the enclave.
                </div>
              </div>
            </div>
          </div>

          <button
            className="btn btn-primary btn-lg"
            disabled={!selectedPolicy || !description}
            onClick={handleSubmit}
            style={{ width: "100%" }}
          >
            🚀 Submit Claim via 0G Chain
          </button>
        </div>
      )}
    </div>
  );
}
